"""empty message

Revision ID: 31752dde3dd7
Revises: f91263acb5d5
Create Date: 2024-05-13 15:00:25.032208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31752dde3dd7'
down_revision = 'f91263acb5d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('under_sea_house_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('under_sea_house_table')
    # ### end Alembic commands ###
